system:
  variables:
    ENV_RELATIONSHIPS: PLATFORM_RELATIONSHIPS
    ENV_ROUTES: PLATFORM_ROUTES
    ENV_VARIABLES: PLATFORM_VARIABLES
    ENV_APPLICATION: PLATFORM_APPLICATION
    ENV_ENVIRONMENT: PLATFORM_ENVIRONMENT
stage:
  deploy:
    CRON_CONSUMERS_RUNNER:
      cron_run: true
