# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.
# More information: https://docs.platform.sh/add-services.html
# Full list of available services: https://docs.platform.sh/add-services.html#available-services

# Magento's Database
mysql:
  type: mariadb:10.6
  disk: 2048

# Magento's cache & session redis instance
# Since our sessions will be sent here, we want to enable persistence so customers are not logged out when we deploy
redis:
  type: redis:7.0

redis-session:
  type: redis-persistent:7.0
  disk: 256

opensearch:
  type: opensearch:2
  disk: 256

rabbitmq:
  type: rabbitmq:3.9
  disk: 512

varnish:
  type: varnish:7.3
  relationships:
    application: 'mymagento:http'
  configuration:
    vcl: !include
      type: string
      path: varnish.vcl
